### ISSUE TITLE
"/usr/bin/csi: No such file or directory" on Arch Linux

### ISSUE THREAD

**Issue by Junker** [mario-goulart/salmonella#6]
```bash
$> salmonella
Error: (shell-command-output) Command ''/usr/bin/csi' -np "(begin (import chicken.platform) (chicken-version))" 2>&1' exited status 127. Output:
sh: line 1: /usr/bin/csi: No such file or directory
```

In Arch Linux csi binary located here: `/usr/bin/chicken-csi` .
Maybe add some environment like `$CHICKEN_CSI`or cli argument like `salmonella --csi-bin=/usr/bin/chicken-csi`

**Comment by mario-goulart** [comment]
Hi.  Thanks for the suggestion and sorry about the issue.  The fix for that has actually already been implemented in https://github.com/mario-goulart/salmonella/commit/6609dc501d6cc7735c5b0c42d1dfb9696585092a , but was not in any released version (the parameter is `--csi`,  though).  I just released 3.1.1 some minutes ago, which contains that change.
